# Generated by Django 3.0.8 on 2020-07-13 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userheader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_id', models.CharField(default='', max_length=200)),
                ('header_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='', max_length=200)),
                ('mainname', models.CharField(default='', max_length=200)),
                ('mainfavicon', models.CharField(default='', max_length=200)),
                ('table_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='', max_length=200)),
                ('main2', models.CharField(default='', max_length=200)),
                ('main3', models.CharField(default='', max_length=200)),
                ('main4', models.CharField(default='', max_length=200)),
                ('main5', models.CharField(default='', max_length=200)),
                ('main6', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
