# Generated by Django 2.2 on 2020-01-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='', max_length=200)),
                ('mainname', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
