# Generated by Django 3.0.3 on 2020-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userlinks_mainfavicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='userheader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(default='', max_length=200)),
                ('header2', models.CharField(default='', max_length=200)),
                ('header3', models.CharField(default='', max_length=200)),
                ('header4', models.CharField(default='', max_length=200)),
                ('header5', models.CharField(default='', max_length=200)),
                ('header6', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
