# Generated by Django 3.0.8 on 2020-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userheader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlinks',
            name='main',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userlinks',
            name='mainfavicon',
            field=models.CharField(default='', max_length=400),
        ),
    ]
